# **Notebook 1 – Introduction to Feature Engineering**

**Dataset Selection**

| Item                        | Details                                                                                                                                                                                            |
| --------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Dataset Name**            | E-Commerce Customer Churn Dataset                                                                                                                                                                  |
| **Source**                  | Kaggle                                                                                                                                    |
| **Domain**                  | E-Commerce                                                                                                                                                                                         |
| **Number of Rows**          | 1,500                                                                                                                                                                                              |
| **Number of Columns**       | 23                                                                                                                                                                                                 |
| **Target Variable**         | `Churn`                                                                                                                                                                                            |
| **Target Type**             | Binary Classification (`Yes` / `No`)                                                                                                                                                               |
| **Customer Information**    | Customer ID, Age, Gender, City, Membership Type                                                                                                                                                    |
| **Transaction Information** | Order Count, Average Order Value, Total Spending, Return Count                                                                                                                                     |
| **Categorical Features**    | Gender, City, Membership Type, Device Type, Payment Method, Preferred Category, Email Opt-In                                                                                                       |
| **Numerical Features**      | Age, Order Count, Average Order Value, Total Spending, Discount %, Review Rating, Support Tickets, Website Visits, App Sessions, etc.                                                              |
| **Date Features**           | Registration Date, Last Purchase Date                                                                                                                                                              |
| **Data Quality Practice**   | Contains a small amount of missing values in selected columns                                                                                                                                      |
| **Reason for Selection**    | The dataset contains numerical, categorical, date, customer, transaction, and target information, making it suitable for practicing Feature Engineering and Feature Selection throughout Sprint 6. |

In [20]:
# Load dataset
import pandas as pd
df = pd.read_csv("ecommerce_customer_churn_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          1500 non-null   object
 1   Age                  1500 non-null   int64
 2   Gender               1500 non-null   object
 3   City                 1500 non-null   object
 4   Membership_Type      1500 non-null   object
 5   Device_Type          1500 non-null   object
 6   Payment_Method       1485 non-null   object
 7   Preferred_Category   1485 non-null   object
 8   Registration_Date    1500 non-null   object
 9   Last_Purchase_Date   1500 non-null   object
 10  Order_Count          1500 non-null   int64
 11  Average_Order_Value  1500 non-null   float64
 12  Total_Spending       1500 non-null   float64
 13  Discount_Percent     1478 non-null   float64
 14  Return_Count         1500 non-null   int64
 15  Review_Rating        1470 non-null   float64
 16  Support_Tickets      1500 non-null   int64
 17  Website_Visits       1500 non-null   int64
 18  App_Sessions         1500 non-null   int64
 19  Email_Opt_In         1500 non-null   object
 20  Coupon_Usage         1500 non-null   int64
 21  Delivery_Delay_Days  1500 non-null   float64
 22  Churn                1500 non-null   object
dtypes: float64(5), int64(7), object(11)
memory usage: 269.7+ KB

## **1. What is a Feature?**

**Understand the Concept**

* A feature is an input variable or column in a dataset.
* It provides useful information to a Machine Learning model.
* Features help the model identify patterns and make predictions.
* Features can be numerical, categorical, date/time, or text.

**Demonstrate the Concept**

**Example:**

* In the E-Commerce Customer Churn dataset, `Age`, `Order_Count`, `Total_Spending`, and `Membership_Type` are features used to predict `Churn`.

**AI/ML Usage:**

* Features are provided as inputs to the Machine Learning model.
* The model learns patterns from these features to predict whether a customer will churn.

In [21]:
# feature columns
features = df.drop("Churn", axis=1)
print("Feature Columns:")
print(features.columns.tolist())

Feature Columns:
['Customer_ID', 'Age', 'Gender', 'City', 'Membership_Type', 'Device_Type', 'Payment_Method', 'Preferred_Category', 'Registration_Date', 'Last_Purchase_Date', 'Order_Count', 'Average_Order_Value', 'Total_Spending', 'Discount_Percent', 'Return_Count', 'Review_Rating', 'Support_Tickets', 'Website_Visits', 'App_Sessions', 'Email_Opt_In', 'Coupon_Usage', 'Delivery_Delay_Days']

**Explanation**

* These features contain information about each customer.
* The model can use these features to learn patterns related to customer churn.

## **2. Feature vs Variable**

**Understand the Concept**

* A variable is any column or value that stores information in a dataset.
* A feature is a variable that we use as an input for a Machine Learning model.
* Some variables may not be useful for prediction.
* For example, `Customer_ID` is a variable, but it may not be a useful feature.

**Demonstrate the Concept**

**Example:**

* In the E-Commerce Customer Churn dataset, `Age`, `Order_Count`, and `Total_Spending` can be used as features.
* `Customer_ID` is a variable used to identify customers, but it does not provide useful information for predicting churn.

**AI/ML Usage:**

* We check the variables in a dataset and select the useful ones as features for the Machine Learning model.

In [22]:
# some variables 
variables = df[["Customer_ID", "Age", "Order_Count", "Total_Spending", "Churn"]]
variables.head()

  Customer_ID  Age  Order_Count  Total_Spending Churn
0   CUST10000   56           10        24259.69   Yes
1   CUST10001   46           12        37587.51    No
2   CUST10002   32           10        13529.39    No
3   CUST10003   60           10        47225.31   Yes
4   CUST10004   25           11        66861.92    No

In [23]:
# features - useful variables for model
features = df[["Age", "Order_Count", "Total_Spending"]]
features.head()

   Age  Order_Count  Total_Spending
0   56           10        24259.69
1   46           12        37587.51
2   32           10        13529.39
3   60           10        47225.31
4   25           11        66861.92

**Explanation**

* `Customer_ID` is a variable used to identify customers.
* `Age`, `Order_Count`, and `Total_Spending` can be useful features for prediction.
* Not every variable in a dataset needs to be used as a feature.

**Justify Your Feature**

* I selected `Age`, `Order_Count`, and `Total_Spending` because they can provide useful information for predicting customer churn.

## **3. Feature vs Target**

**Understand the Concept**

* Features are the input columns given to the Machine Learning model.
* The target is the output that we want the model to predict.
* Features are usually represented as `X`.
* The target is usually represented as `y`.

**Demonstrate the Concept**

**Example:**

* In the E-Commerce Customer Churn dataset, `Age`, `Order_Count`, and `Total_Spending` are features.
* `Churn` is the target because we want to predict whether a customer will leave.

**AI/ML Usage:**

* The model learns the relationship between the features and the target.
* During prediction, the model uses the feature values to predict the target.

In [24]:
# features and target

X = df[["Age", "Order_Count", "Total_Spending", "Membership_Type"]]
y = df["Churn"]

print("Features (X):")
print(X.head(1))

print("\nTarget (y):")
print(y.head(1))

Features (X):
   Age  Order_Count  Total_Spending Membership_Type
0   56           10        24259.69          Silver

Target (y):
0    Yes
Name: Churn, dtype: object

**Explanation**

* `X` contains the input features used by the model.
* `y` contains the target that the model needs to predict.
* Here, the model uses customer information to predict `Churn`.

**Justify Your Feature**

* I selected these features because they can provide useful information for predicting customer churn.

## **4. What is Feature Engineering?**

**Understand the Concept**

* Feature Engineering means creating or changing features to make them more useful for a Machine Learning model.
* We can create new features from existing columns.
* We can also transform existing features into a better form.
* The main goal is to give the model useful information to learn from.

**Demonstrate the Concept**

**Example:**

* In the E-Commerce dataset, we can create `Average_Spending_Per_Order` using `Total_Spending` and `Order_Count`.
* This gives information about how much a customer spends on each order.

**AI/ML Usage:**

* Feature Engineering helps the model understand important patterns in the data.
* Well-designed features can improve prediction performance.

In [25]:
# Create a new feature: Average Spending Per Order

df["Average_Spending_Per_Order"] = round((df["Total_Spending"] / df["Order_Count"]),2)
df[["Total_Spending", "Order_Count", "Average_Spending_Per_Order"]].head()

   Total_Spending  Order_Count  Average_Spending_Per_Order
0        24259.69           10                     2425.97
1        37587.51           12                     3132.29
2        13529.39           10                     1352.94
3        47225.31           10                     4722.53
4        66861.92           11                     6078.36

**Explanation**

* `Average_Spending_Per_Order` is created using `Total_Spending` and `Order_Count`.
* It shows how much a customer spends on average for each order.

**Justify Your Feature**

* I created this feature because it gives useful information about a customer's average spending behavior.

## **5. Why Feature Engineering?**

**Understand the Concept**

* Raw data may not contain all the information needed by a Machine Learning model.
* Feature Engineering helps us create useful information from existing data.
* Good features can make patterns easier for the model to learn.
* It can improve model performance and help us understand the data better.

## **6. Importance of Domain Knowledge**

**Understand the Concept**

* Domain knowledge means understanding the business or field related to the data.
* It helps us create features that have real-world meaning.
* A feature may be useful when we understand how the business works.
* Good domain knowledge helps us avoid creating meaningless features.

**Demonstrate the Concept**

**Example:**

* In an E-Commerce business, customers who have not purchased for a long time may be more likely to churn.
* We can create a `Days_Since_Last_Purchase` feature using the customer's last purchase date.

**AI/ML Usage:**

* Domain knowledge helps us create features that represent real customer behavior.
* These meaningful features can help the model make better predictions.

In [26]:
# Convert Last_Purchase_Date to datetime
df["Last_Purchase_Date"] = pd.to_datetime(df["Last_Purchase_Date"])

# Create a reference date
reference_date = pd.Timestamp("2026-01-01")

# Create Days Since Last Purchase feature
df["Days_Since_Last_Purchase"] = (reference_date - df["Last_Purchase_Date"]).dt.days
df[["Customer_ID", "Last_Purchase_Date","Days_Since_Last_Purchase", "Churn"]].head()

  Customer_ID Last_Purchase_Date  Days_Since_Last_Purchase Churn
0   CUST10000         2022-07-06                      1275   Yes
1   CUST10001         2025-01-26                       340    No
2   CUST10002         2025-12-31                         1    No
3   CUST10003         2022-02-02                      1429   Yes
4   CUST10004         2025-12-31                         1    No

**Explanation**

* `Days_Since_Last_Purchase` shows how many days have passed since the customer's last purchase.
* This feature represents customer recency, which is important in E-Commerce.
* A higher value may indicate that a customer has become less active.

**Justify Your Feature**

* I created this feature because recent customer activity can provide useful information for predicting churn.

## **7. Good Features vs Bad Features**

**Understand the Concept**

* A good feature provides useful information for the model.
* A bad feature may be irrelevant, noisy, duplicated, or misleading.
* Good features should have a meaningful relationship with the target.
* Not every column in a dataset is useful for Machine Learning.

**Demonstrate the Concept**

**Example:**

* `Total_Spending` can be a good feature because it provides information about customer behavior.
* `Customer_ID` may be a bad feature because it only identifies the customer and does not describe their behavior.

**AI/ML Usage:**

* Good features help the model learn useful patterns.
* Removing bad features can reduce unnecessary information and improve model performance.

In [27]:
# Compare feature with an irrelevant variable

feature_check = df[ ["Customer_ID", "Total_Spending", "Order_Count", "Churn"]]
feature_check.head()

  Customer_ID  Total_Spending  Order_Count Churn
0   CUST10000        24259.69           10   Yes
1   CUST10001        37587.51           12    No
2   CUST10002        13529.39           10    No
3   CUST10003        47225.31           10   Yes
4   CUST10004        66861.92           11    No

In [28]:
# number of unique values

print("Customer_ID unique values:", df["Customer_ID"].nunique())
print("Total_Spending unique values:", df["Total_Spending"].nunique())
print("Order_Count unique values:", df["Order_Count"].nunique())

Customer_ID unique values: 1500
Total_Spending unique values: 1498
Order_Count unique values: 18

**Explanation**

* `Customer_ID` has a unique value for almost every customer, so it is mainly used for identification.
* `Total_Spending` and `Order_Count` provide information about customer behavior.
* Therefore, `Total_Spending` and `Order_Count` are more useful features for predicting churn.

**Justify Your Feature**

* I selected `Total_Spending` and `Order_Count` because they provide useful information about customer behavior.

## **8. Feature Engineering Workflow**

**Understand the Concept**

* Feature Engineering follows a series of steps to prepare useful features.
* First, we understand the data and identify the available features.
* Then, we create, transform, and select useful features.
* Finally, we check the features for leakage before using them in a model.

**Demonstrate the Concept**

**Example:**

* For customer churn prediction, we can understand customer data, create `Average_Spending_Per_Order`, create `Days_Since_Last_Purchase`, and select useful features.

**AI/ML Usage:**

* A proper workflow helps create reliable features and prepares the dataset for Machine Learning.

In [29]:
# View the current dataset columns

df.columns.tolist()

['Customer_ID',
 'Age',
 'Gender',
 'City',
 'Membership_Type',
 'Device_Type',
 'Payment_Method',
 'Preferred_Category',
 'Registration_Date',
 'Last_Purchase_Date',
 'Order_Count',
 'Average_Order_Value',
 'Total_Spending',
 'Discount_Percent',
 'Return_Count',
 'Review_Rating',
 'Support_Tickets',
 'Website_Visits',
 'App_Sessions',
 'Email_Opt_In',
 'Coupon_Usage',
 'Delivery_Delay_Days',
 'Churn',
 'Average_Spending_Per_Order',
 'Days_Since_Last_Purchase']

In [30]:
# Check basic information about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Customer_ID                 1500 non-null   object
 1   Age                         1500 non-null   int64
 2   Gender                      1500 non-null   object
 3   City                        1500 non-null   object
 4   Membership_Type             1500 non-null   object
 5   Device_Type                 1500 non-null   object
 6   Payment_Method              1485 non-null   object
 7   Preferred_Category          1485 non-null   object
 8   Registration_Date           1500 non-null   object
 9   Last_Purchase_Date          1500 non-null   datetime64[ns]
 10  Order_Count                 1500 non-null   int64
 11  Average_Order_Value         1500 non-null   float64
 12  Total_Spending              1500 non-null   float64
 13  Discount_Percent            1478 non-null   float64
 14  Return_Count                1500 non-null   int64
 15  Review_Rating               1470 non-null   float64
 16  Support_Tickets             1500 non-null   int64
 17  Website_Visits              1500 non-null   int64
 18  App_Sessions                1500 non-null   int64
 19  Email_Opt_In                1500 non-null   object
 20  Coupon_Usage                1500 non-null   int64
 21  Delivery_Delay_Days         1500 non-null   float64
 22  Churn                       1500 non-null   object
 23  Average_Spending_Per_Order  1500 non-null   float64
 24  Days_Since_Last_Purchase    1500 non-null   int64
dtypes: datetime64[ns](1), float64(6), int64(8), object(10)
memory usage: 293.1+ KB

In [31]:
# Check the target distribution

df["Churn"].value_counts()

Churn
No     983
Yes    517
Name: count, dtype: int64

**Explanation**

* `columns` helps us understand the available variables.
* `info()` shows data types and missing values.
* Checking the target helps us understand the prediction problem.

**Justify Your Feature**

* I follow this workflow to understand the data and create reliable features before model training.

## **9. Feature Creation**

**Understand the Concept**

* Feature Creation means creating a new feature from existing data.
* New features can combine one or more columns.
* The new feature should provide useful information that is not directly available.
* Feature Creation often uses formulas or business rules.

**Demonstrate the Concept**

**Example:**

* We can combine `Order_Count` and `Total_Spending` to create `Average_Spending_Per_Order`.

**AI/ML Usage:**

* New features can give the model additional information about customer behavior.

In [32]:
# Create a new feature 

df["Average_Spending_Per_Order"] = (df["Total_Spending"] / df["Order_Count"])

df[["Order_Count", "Total_Spending", "Average_Spending_Per_Order"]].head()

   Order_Count  Total_Spending  Average_Spending_Per_Order
0           10        24259.69                 2425.969000
1           12        37587.51                 3132.292500
2           10        13529.39                 1352.939000
3           10        47225.31                 4722.531000
4           11        66861.92                 6078.356364

**Explanation**

* The new feature calculates the average spending for each order.
* It combines information from two existing columns.
* This gives a clearer view of customer spending behavior.

**Justify Your Feature**

* I created this feature because average spending can help understand customer purchasing behavior.

## **10. Feature Transformation**

**Understand the Concept**

* Feature Transformation means changing the form or scale of an existing feature.
* Transformation can make data easier for a model to work with.
* Common transformations include scaling, logarithmic transformation, and normalization.
* The choice of transformation depends on the data and Machine Learning algorithm.

**Demonstrate the Concept**

**Example:**

* `Total_Spending` may contain values with a large range.
* We can use a logarithmic transformation to reduce the effect of very large values.

**AI/ML Usage:**

* Feature transformation can make numerical features more suitable for Machine Learning models.

In [33]:
import numpy as np

# Create a log-transformed spending feature

df["Log_Total_Spending"] = np.log1p(df["Total_Spending"])

df[["Total_Spending", "Log_Total_Spending"]].head()

   Total_Spending  Log_Total_Spending
0        24259.69           10.096613
1        37587.51           10.534454
2        13529.39            9.512694
3        47225.31           10.762706
4        66861.92           11.110400

**Explanation**

* `log1p()` applies a logarithmic transformation to `Total_Spending`.
* It reduces the effect of very large spending values.
* The original feature is kept so we can compare both versions.

**Justify Your Feature**

* I created this transformed feature because it can reduce the impact of highly large spending values.

## **11. Feature Selection**

**Understand the Concept**

* Feature Selection means choosing the most useful features for a Machine Learning model.
* Some features may be irrelevant or provide very little useful information.
* Removing unnecessary features can make the model simpler.
* Feature selection can also reduce training time and unwanted noise.

**Demonstrate the Concept**

**Example:**
m
* `Age`, `Order_Count`, and `Total_Spending` may be useful for predicting churn.
* `Customer_ID` is mainly an identifier and may not be useful for prediction.

**AI/ML Usage:**

* Selected features are used as model inputs.
* Feature selection helps the model focus on useful information.

In [34]:
# Select useful features for a future ML model

selected_features = df[["Age", "Order_Count","Total_Spending","Average_Spending_Per_Order","Days_Since_Last_Purchase","Membership_Type"]]
selected_features.head()

,Age,Order_Count,Total_Spending,Average_Spending_Per_Order,Days_Since_Last_Purchase,Membership_Type
0,56,10,24259.69,2425.969000,1275,Silver
1,46,12,37587.51,3132.292500,340,Gold
2,32,10,13529.39,1352.939000,1,Basic
3,60,10,47225.31,4722.531000,1429,Basic
4,25,11,66861.92,6078.356364,1,Basic

**Explanation**

* The selected columns contain information about customer characteristics and behavior.
* `Customer_ID` is not included because it is mainly an identifier.
* Feature selection will be explored in more detail in Notebook 9.

**Justify Your Feature**

* I selected these features because they provide useful information about customer behavior and churn.

## **12. Feature Extraction**

**Understand the Concept**

* Feature Extraction means extract useful information from existing data.
* It can convert complex or detailed data into simpler features.
* The extracted information can be used as input for a Machine Learning model.
* Dates, text, and other complex data can be sources for feature extraction.

**Demonstrate the Concept**

**Example:**

* From `Last_Purchase_Date`, we can extract the day, month, or day of the week.
* These extracted values can provide information about customer purchasing behavior.

**AI/ML Usage:**

* Feature extraction converts useful information from raw data into features that a model can understand.

In [35]:
# Extract useful information from Last_Purchase_Date

df["Last_Purchase_Month"] = df["Last_Purchase_Date"].dt.month
df["Last_Purchase_Day"] = df["Last_Purchase_Date"].dt.day
df["Last_Purchase_Weekday"] = df["Last_Purchase_Date"].dt.dayofweek

df[["Last_Purchase_Date","Last_Purchase_Month","Last_Purchase_Day","Last_Purchase_Weekday"]].head()

,Last_Purchase_Date,Last_Purchase_Month,Last_Purchase_Day,Last_Purchase_Weekday
0,2022-07-06,7,6,2
1,2025-01-26,1,26,6
2,2025-12-31,12,31,2
3,2022-02-02,2,2,2
4,2025-12-31,12,31,2

**Explanation**

* Month, day, and weekday are extracted from the purchase date.
* These features provide additional information about when customers made their purchases.
* Date and time feature engineering will be covered in detail in Notebook 4.

**Justify Your Feature**

* I extracted these features because purchase timing may provide useful information about customer behavior.

## **13. Feature Leakage**

**Understand the Concept**

* Feature Leakage happens when a feature contains information that should not be available when making a prediction.
* Leakage can make model performance look better than it really is.
* Leakage can happen when future information or target information is included in the features.
* Features should only use information that would be available at prediction time.

**Demonstrate the Concept**

**Example:**

* Suppose we are predicting whether a customer will churn.
* Using a feature created after the customer has already churned can cause leakage.
* For example, `Churn_Reason` would not be available before the churn prediction.

**AI/ML Usage:**

* Preventing leakage helps ensure that the model learns from realistic information.
* Leakage checks should be performed before training the final model.

In [36]:
# Example of a safe feature

df["Days_Since_Last_Purchase"] = ( pd.Timestamp("2026-01-01") - df["Last_Purchase_Date"]).dt.days
df[["Last_Purchase_Date", "Days_Since_Last_Purchase", "Churn"]].head()

  Last_Purchase_Date  Days_Since_Last_Purchase Churn
0         2022-07-06                      1275   Yes
1         2025-01-26                       340    No
2         2025-12-31                         1    No
3         2022-02-02                      1429   Yes
4         2025-12-31                         1    No

**Explanation**

* `Days_Since_Last_Purchase` uses the customer's purchase date to calculate recency.
* The feature does not directly use the `Churn` target.
* We must make sure that the reference date represents the prediction time and does not use future information.

**Justify Your Feature**

* I selected this feature because it uses available customer activity information without directly using the target.