# **Notebook 2 – Numerical Feature Engineering**

In [18]:
# Load dataset
import pandas as pd
df = pd.read_csv("online_retail_sales_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   object
 1   Customer_ID       2000 non-null   object
 2   Order_Date        2000 non-null   object
 3   Product_Category  2000 non-null   object
 4   Region            2000 non-null   object
 5   Payment_Method    2000 non-null   object
 6   Customer_Segment  2000 non-null   object
 7   Customer_Age      2000 non-null   int64
 8   Quantity          2000 non-null   int64
 9   Unit_Price        2000 non-null   float64
 10  Discount_Percent  1970 non-null   float64
 11  Shipping_Cost     1980 non-null   float64
 12  Product_Rating    1960 non-null   float64
 13  Delivery_Days     2000 non-null   int64
 14  Return_Flag       2000 non-null   object
 15  Cost_Price        2000 non-null   float64
 16  Gross_Sales       2000 non-null   float64
 17  Discount_Amount   2000 non-null   float64
 18  Net_Sales         2000 non-null   float64
 19  Profit            2000 non-null   float64
dtypes: float64(9), int64(3), object(8)
memory usage: 312.6+ KB

## **1. Mathematical Transformations**

**Understand the Concept**

* Mathematical transformation means using existing numbers to create new information.
* We can use simple operations like `+`, `-`, `×`, and `÷`.
* These operations help create useful numerical features.

## **2. Addition**

**Understand the Concept**

* Addition combines two or more numerical values.
* It can create a new feature that represents a total value.
* Use addition when different values contribute to the same measurement.

**Demonstrate the Concept**

**Example:**

* Add `Net_Sales` and `Shipping_Cost` to find the total amount including shipping.

**AI/ML Usage:**

* Addition can create total-value features that give the model more useful information.

In [19]:
# addition
df["Total_Amount_With_Shipping"] = (df["Net_Sales"] + df["Shipping_Cost"])
df[["Net_Sales", "Shipping_Cost", "Total_Amount_With_Shipping"]].head()

   Net_Sales  Shipping_Cost  Total_Amount_With_Shipping
0    1402.01         142.63                     1544.64
1    2148.67         130.99                     2279.66
2     755.74         118.53                      874.27
3    1192.25         102.94                     1295.19
4     642.46          81.43                      723.89

## **3. Subtraction**

**Understand the Concept**

* Subtraction finds the difference between two numerical values.
* It helps us understand the gap between two amounts.
* Use subtraction when one value needs to be compared with another.

**Demonstrate the Concept**

**Example:**

* Subtract `Cost_Price` from `Unit_Price` to find the profit amount per item before other costs.

**AI/ML Usage:**

* Subtraction can create features that show differences or gaps between important values.

In [20]:
# subtraction

df["Price_Margin_Per_Item"] = (df["Unit_Price"] - df["Cost_Price"])
df[["Unit_Price", "Cost_Price", "Price_Margin_Per_Item"]].head()

   Unit_Price  Cost_Price  Price_Margin_Per_Item
0      174.12       88.79                  85.33
1      317.56      230.32                  87.24
2      294.19      167.30                 126.89
3      196.02      147.47                  48.55
4       80.00       56.64                  23.36

**Justify Your Feature**

* I created this feature because it shows the difference between selling price and cost price.

## **4. Division**

**Understand the Concept**

* Division compares one value with another.
* It can help calculate an average or value per unit.
* Use division when one value depends on the size of another value.

**Demonstrate the Concept**

*m*Example:**

* Divide `Net_Sales` by `Quantity` to find the sales amount per item.

**AI/ML Usage:**

* Division can create per-unit features that give the model more useful information.

In [21]:
# division 
df["Sales_Per_Item"] = (df["Net_Sales"] / df["Quantity"])
df[["Net_Sales", "Quantity", "Sales_Per_Item"]].head()

   Net_Sales  Quantity  Sales_Per_Item
0    1402.01        10      140.201000
1    2148.67         7      306.952857
2     755.74         3      251.913333
3    1192.25         7      170.321429
4     642.46         9       71.384444

## **5. Ratios**

**Understand the Concept**

* A ratio compares two numerical values.
* It shows how one value relates to another.
* Ratios are useful when the relationship between two values is important.

**Demonstrate the Concept**

**Example:**

* Compare `Profit` with `Net_Sales` to understand profit relative to sales.

**AI/ML Usage:**

* Ratio features help the model understand relationships between numerical values.

In [22]:
# ratio
df["Profit_to_Sales_Ratio"] = (df["Profit"] / df["Net_Sales"])
df[    ["Profit", "Net_Sales", "Profit_to_Sales_Ratio"]].head()

   Profit  Net_Sales  Profit_to_Sales_Ratio
0  371.48    1402.01               0.264962
1  405.44    2148.67               0.188693
2  135.31     755.74               0.179043
3   57.02    1192.25               0.047826
4   51.27     642.46               0.079803

## **6. Percentages**

**Understand the Concept**

* A percentage shows a value as part of another value.
* It makes comparisons easier to understand.
* Percentages are useful for measuring discounts, costs, or contributions.

**Demonstrate the Concept**

**Example:**

* Calculate shipping cost as a percentage of `Net_Sales`.

**AI/ML Usage:**

* Percentage features help the model understand the relative contribution of different values.

In [23]:
# Calculate shipping cost percentage

df["Shipping_Cost_Percent"] = (df["Shipping_Cost"] / df["Net_Sales"]) * 100
df[["Shipping_Cost", "Net_Sales", "Shipping_Cost_Percent"]].head()

   Shipping_Cost  Net_Sales  Shipping_Cost_Percent
0         142.63    1402.01              10.173251
1         130.99    2148.67               6.096329
2         118.53     755.74              15.683965
3         102.94    1192.25               8.634095
4          81.43     642.46              12.674719

## **7. Differences**

**Understand the Concept**

* Difference measures the gap between two numerical values.
* It helps us compare actual values with another reference value.
* Differences can show increases, decreases, or gaps.

**Demonstrate the Concept**

**Example:**

* Compare `Unit_Price` with `Cost_Price` to find the difference between selling and cost price.

**AI/ML Usage:**

* Difference features help the model understand gaps between related numerical values.

In [24]:
# Calculate the difference between selling price and cost price
df["Price_Difference"] = (df["Unit_Price"] - df["Cost_Price"])
df[["Unit_Price", "Cost_Price", "Price_Difference"]].head()

   Unit_Price  Cost_Price  Price_Difference
0      174.12       88.79             85.33
1      317.56      230.32             87.24
2      294.19      167.30            126.89
3      196.02      147.47             48.55
4       80.00       56.64             23.36

## **8. Aggregations**

**Understand the Concept**

* Aggregation combines multiple values into a summary value.
* Common aggregations include sum, mean, minimum, and maximum.
* Aggregations help summarize numerical information.

**Demonstrate the Concept**

**Example:**

* Calculate the average of `Unit_Price`, `Cost_Price`, and `Shipping_Cost` for each transaction.

**AI/ML Usage:**

* Aggregated features summarize information and can provide useful inputs to a model.

In [25]:
# Calculate the average value of selected numerical columns

df["Average_Cost_Measure"] = df[["Unit_Price", "Cost_Price", "Shipping_Cost"]].mean(axis=1)
df[["Unit_Price", "Cost_Price", "Shipping_Cost","Average_Cost_Measure"]].head()

   Unit_Price  Cost_Price  Shipping_Cost  Average_Cost_Measure
0      174.12       88.79         142.63                135.18
1      317.56      230.32         130.99                226.29
2      294.19      167.30         118.53                193.34
3      196.02      147.47         102.94                148.81
4       80.00       56.64          81.43                 72.69


**Justify Your Feature**

* I created this feature because it summarizes multiple cost-related values into one feature.

## **9. Log Transformation**

**Understand the Concept**

* Log transformation changes large numerical values into a smaller scale.
* It is useful when data is highly skewed.
* It can reduce the effect of extremely large values.

**Demonstrate the Concept**

**Example:**

* `Gross_Sales` may contain some very large transaction values, so a log transformation can reduce their effect.

**AI/ML Usage:**

* Log transformation can help some Machine Learning models work better with highly skewed numerical features.

In [26]:
import numpy as np
# log transformation
df["Log_Gross_Sales"] = np.log1p(df["Gross_Sales"])
df[["Gross_Sales", "Log_Gross_Sales"]].head()

   Gross_Sales  Log_Gross_Sales
0      1741.20         7.462904
1      2222.92         7.707027
2       882.57         6.783971
3      1372.14         7.224855
4       720.00         6.580639

**Justify Your Feature**

* I created this feature because it helps reduce the effect of highly large sales values.

## **10. Square Root Transformation**

**Understand the Concept**

* Square root transformation reduces the size of large numerical values.
* It is useful for reducing moderate skewness.
* It is less aggressive than log transformation.

**Demonstrate the Concept**

**Example:**

* Apply a square root transformation to `Quantity`.

**AI/ML Usage:**

* Square root transformation can make a numerical feature less skewed and easier for some models to use.

In [27]:
# square root transformation
df["Sqrt_Quantity"] = np.sqrt(df["Quantity"])
df[["Quantity", "Sqrt_Quantity"]].head()

   Quantity  Sqrt_Quantity
0        10       3.162278
1         7       2.645751
2         3       1.732051
3         7       2.645751
4         9       3.000000

## **11. Power Transformation**

**Understand the Concept**

* Power transformation changes the scale of a numerical feature using a power.
* It can help change the shape of a feature's distribution.
* The power used depends on the data and the purpose of the transformation.

**Demonstrate the Concept**

**Example:**

* Apply a square power to `Product_Rating` to create a new transformed feature.

**AI/ML Usage:**

* Power transformations can help create features with a different scale or distribution.

In [28]:
# power transformation
df["Rating_Squared"] = df["Product_Rating"] ** 2
df[["Product_Rating", "Rating_Squared"]].head()

   Product_Rating  Rating_Squared
0             3.1            9.61
1             2.6            6.76
2             5.0           25.00
3             3.5           12.25
4             3.9           15.21

## **12. Absolute Difference**

**Understand the Concept**

* Absolute difference measures the size of a difference.
* It always gives a positive value.
* It is useful when the direction of the difference is not important.

**Demonstrate the Concept**

**Example:**

* Find the absolute difference between `Unit_Price` and `Cost_Price`.

**AI/ML Usage:**

* Absolute difference helps the model understand the size of a gap between two features.

In [29]:
# absolute price difference
df["Absolute_Price_Difference"] = (df["Unit_Price"] - df["Cost_Price"]).abs()
df[["Unit_Price", "Cost_Price", "Absolute_Price_Difference"]].head()

   Unit_Price  Cost_Price  Absolute_Price_Difference
0      174.12       88.79                      85.33
1      317.56      230.32                      87.24
2      294.19      167.30                     126.89
3      196.02      147.47                      48.55
4       80.00       56.64                      23.36

**Explanation**

* The absolute value removes the negative sign from any difference.
* The new feature shows the size of the price gap.

**Justify Your Feature**

* I created this feature because it clearly shows the size of the difference between selling and cost price.

## **13. Relative Difference**

**Understand the Concept**

* Relative difference compares a difference with a reference value.
* It shows how large the difference is relative to that value.
* It is useful when values have different scales.

**Demonstrate the Concept**

**Example:**

* Compare the difference between `Unit_Price` and `Cost_Price` relative to `Cost_Price`.

**AI/ML Usage:**

* Relative difference helps the model understand the size of a difference in relative terms.

In [30]:
# Calculate relative price difference

df["Relative_Price_Difference"] = ((df["Unit_Price"] - df["Cost_Price"])/ df["Cost_Price"])
df[["Unit_Price", "Cost_Price", "Relative_Price_Difference"]].head()

   Unit_Price  Cost_Price  Relative_Price_Difference
0      174.12       88.79                   0.961032
1      317.56      230.32                   0.378777
2      294.19      167.30                   0.758458
3      196.02      147.47                   0.329220
4       80.00       56.64                   0.412429

**Explanation**

* The price difference is divided by the cost price.
* The new feature shows the price difference relative to the cost.

**Justify Your Feature**

* I created this feature because it shows the price difference in relative terms.

## **14. Rate Features**

**Understand the Concept**

* A rate feature measures an amount relative to another quantity.
* It can show activity per item, day, or other unit.
* Rates help compare transactions of different sizes.

**Demonstrate the Concept**

**Example:**

* Calculate sales per delivery day using `Net_Sales` and `Delivery_Days`.

**AI/ML Usage:**

* Rate features help the model compare performance across different quantities or time periods.

In [31]:
# Calculate sales per delivery day

df["Sales_Per_Delivery_Day"] = (df["Net_Sales"] / df["Delivery_Days"])
df[["Net_Sales", "Delivery_Days", "Sales_Per_Delivery_Day"]].head()

   Net_Sales  Delivery_Days  Sales_Per_Delivery_Day
0    1402.01              3              467.336667
1    2148.67              6              358.111667
2     755.74              4              188.935000
3    1192.25              8              149.031250
4     642.46              1              642.460000


**Justify Your Feature**

* I created this feature because it compares sales value with delivery time.

## **15. Normalized Features**

**Understand the Concept**

* Normalization changes numerical values to a common scale.
* It helps features with different ranges become easier to compare.
* Min-Max normalization usually converts values to a range between 0 and 1.

**Demonstrate the Concept**

**Example:**

* `Gross_Sales` can have a much larger range than `Product_Rating`.
* We can normalize `Gross_Sales` to a 0–1 range.

**AI/ML Usage:**

* Normalized features are useful for algorithms that are sensitive to feature scale, such as KNN and some gradient-based models.

In [32]:
# Normalize - Gross_Sales using Min-Max scaling

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df["Normalized_Gross_Sales"] = scaler.fit_transform(df[["Gross_Sales"]])
df[["Gross_Sales", "Normalized_Gross_Sales"]].head()

   Gross_Sales  Normalized_Gross_Sales
0      1741.20                0.141343
1      2222.92                0.182330
2       882.57                0.068286
3      1372.14                0.109941
4       720.00                0.054454

**Explanation**

* `MinMaxScaler` converts `Gross_Sales` to a range between 0 and 1.
* The original values are kept unchanged.
* The normalized feature makes the values easier to compare with other scaled features.

**Justify Your Feature**

* I created this feature because it puts sales values on a common scale for Machine Learning.